#!/bin/bash


# Setting ANSI colors
lightred='\033[0;91m'
lightgreen='\033[92m'
no_color='\033[0m'
bold='\033[1m'
normal='\033[0m'
underline='\033[4m'

# System variables/values set up.
fqdn=`hostname -f`
ip=`hostname -I | awk '{ print $1 }'`
running_procs=`ps aux | wc -l`
# cur_user=`whoami`
cur_time=`date | awk '{ print $4,$5 }'`
cur_date=`date | awk '{ print $3,$2,$6 }'`
bash_ver=`bash --version | awk 'NR==1 { print $4}'`
kernel_ver=`uname -r`
cpu_info=`cat /proc/cpuinfo | awk 'NR==5 { print $4,$5,$6,$7,$8,$9 }'`
mem_stats=`free -m | awk 'NR==2 { print $3 "MBs (free)", "/" , $2 "MBs (total)"  }'`
total_packages=`dpkg-query -l | wc -l`
total_uptime=`uptime -p | awk '{ print $2,$3,$4,$5}'`


echo -e "\n\t $bold$underline System Information: $normal \n"
echo -e "$lightred FQDN is: $lightgreen$fqdn"
echo -e "$lightred Hostname is: $lightgreen `hostname`"
echo -e "$lightred IP is: $lightgreen$ip"
echo -e "$lightred Shell Version: $lightgreen$bash_ver"
echo -e "$lightred Kernel Version: $lightgreen$kernel_ver"
echo -e "$lightred CPU type: $lightgreen$cpu_info"
echo -e "$lightred Memory Usage: $lightgreen$mem_stats"
echo -e "$lightred Running processes: $lightgreen$running_procs"
echo -e "$lightred Installed packages: $lightgreen$total_packages"
# echo -e "$lightred Current User: $lightgreen$cur_user"
echo -e "$lightred Current Time: $lightgreen$cur_time"
echo -e "$lightred Current Date: $lightgreen$cur_date"
echo -e "$lightred Up Since: $lightgreen$total_uptime\n $no_color"


# DevOps variables/values set up.
jenkins_ver=`java -jar /usr/share/jenkins/jenkins.war --version`
terraform_ver=`terraform --version | awk 'NR==1 { print $2 }'`
ansible_ver=`sudo ansible --version | awk 'NR==1 { print $2}'`
docker_ver=`docker --version | awk '{ print $3,$4,$5}'`
awscli_ver=`aws --version`
python3_ver=`python3 --version | awk '{ print $2 }'`
git_ver=`git --version | awk '{ print $3 }'`
svn_ver=`svn --version | awk 'NR==1 { print $3,$4 }'`

echo -e "\n\t $bold$underline DevOps Toolstack: $normal \n"
echo -e "$lightred Jenkins Version:\t $lightgreen$jenkins_ver"
echo -e "$lightred Terraform Version:\t $lightgreen$terraform_ver"
echo -e "$lightred Ansible Version:\t $lightgreen$ansible_ver"
echo -e "$lightred Docker Version:\t $lightgreen$docker_ver"
echo -e "$lightred AWS-CLI Version:\t $lightgreen$awscli_ver"
echo -e "$lightred Python3 Version:\t $lightgreen$python3_ver"
echo -e "$lightred Git Version:\t\t $lightgreen$git_ver"
echo -e "$lightred SVN Version:\t\t $lightgreen$svn_ver\n $no_color"

# Maintainer/creater support info

email="am900820@gmail.com"
github_url=https://github.com/Tech-Overlord/devopsubuntu1804

echo -e "\n\t $bold$underline Maintainer's Information: $normal \n"
echo -e "$lightred Name:\t\t $lightgreen Ali Muhammad"
echo -e "$lightred GitHub URL:\t $lightgreen$github_url"
echo -e "$lightred E-mail:\t $lightgreen$email\n $no_color"
